# pytest-testmon-bug-none-in-cache
Trying to reproduce an issue with pytest-testmon mishandling `__init__.py` files in the cache, see https://github.com/tarpas/pytest-testmon/issues/145.

See https://travis-ci.org/TauPan/pytest-testmon-bug-none-in-cache for build results.
